services:
  - type: web
    name: foundwise-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    rootDir: Backend
